---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
          datacenter: FortMeade
          bind_interface: eth0
          advertise_interface: eth0
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: cluster
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service_mode: cluster
        bootstrap_expect: 1
